In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

**Tensorflow usa Autodiferenciación**

**Rastrea todas las operaciones hechas sobre los tensores, en un grafo computacional, y asi obtiene los gradientes correspondientes**

In [ ]:
conv2d = tf.keras.layers.Conv2D(
    filters=1,
    kernel_size=(3,3),
    strides=(1,1),
    padding='same',
    data_format='channels_last',
    dilation_rate=(1,1),
    groups=1,
    activation=None,
    use_bias=True,
    kernel_initializer= tf.keras.initializers.RandomNormal(),
    bias_initializer= tf.keras.initializers.Zeros(),
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
)

In [ ]:
# HYPERPARAMETERS
inputShape = tf.TensorShape([1,3,3,1])
outputShape = conv2d.compute_output_shape(inputShape)
conv2d.build(input_shape=inputShape)

In [ ]:
inputTensor = tf.Variable(tf.random.normal(inputShape,mean=0.0,stddev=1.0))
outputTensor = conv2d.call(inputTensor)

In [ ]:
initKernel = conv2d.get_weights()[0]
initBias = conv2d.get_weights()[1]
print("INPUT \n", inputTensor[0,:,:,0].numpy())
print("OUTPUT \n", outputTensor[0,:,:,0].numpy())
print("KERNEL \n", conv2d.get_weights()[0][:,:,0,0])
print("BIAS", conv2d.get_weights()[1])

INPUT 
 [[-0.86981535  0.72262895  0.12202864]
 [ 0.55280834 -1.5172452  -0.53692394]
 [ 0.31984892 -0.12807836  0.14827271]]
OUTPUT 
 [[-0.06801372  0.03966638  0.08015612]
 [-0.22591563 -0.03328112  0.00204738]
 [ 0.17835513  0.00651862  0.1605095 ]]
KERNEL 
 [[-0.09956098 -0.00119793 -0.1220255 ]
 [-0.05152094  0.01489945  0.08503254]
 [-0.06559259 -0.02988958  0.06589424]]
BIAS [0.]


In [ ]:
conv2d.set_weights([tf.Variable(tf.ones_like(initKernel)),initBias])
outputTensor = conv2d.call(inputTensor)

In [ ]:
print("CONFIG: ", conv2d.get_config())
print("BUILD CONFIG: ", conv2d.get_build_config())

CONFIG:  {'name': 'conv2d', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'filters': 1, 'kernel_size': (3, 3), 'strides': (1, 1), 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': (1, 1), 'groups': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'RandomNormal', 'config': {'mean': 0.0, 'stddev': 0.05, 'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
BUILD CONFIG:  {'input_shape': TensorShape([1, 3, 3, 1])}
